repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args:
          - '--print-width=100'
          - '--single-quote'
          - '--trailing-comma=all'
        exclude: 'CookieMonster(Dev)?.js'
