repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args:
          - '--print-width=100'
          - '--single-quote'
          - '--trailing-comma=all'
        exclude: &build 'CookieMonster(Dev)?.js(.map)?'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: *build
      - id: end-of-file-fixer
        exclude: *build
